/* tslint:disable */
/* eslint-disable */
/**
 * British Geological Survey Sensors API
 * The British Geological Survey (BGS) Sensor API uses Version v1.1 of the OGC SensorThings API.<br><br> Paths/Endpoints that are not currently in use have been excluded, i.e. those relating to Actuators, MultiDatastreams, Tasks and TaskingCapabilities.<br><br> HistoricalLocations have also been removed.<br><br>
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime'
import type {
  FeatureOfInterest,
  FeaturesOfInterest,
  Observations
} from '../models/index'
import {
  FeatureOfInterestFromJSON,
  FeatureOfInterestToJSON,
  FeaturesOfInterestFromJSON,
  FeaturesOfInterestToJSON,
  ObservationsFromJSON,
  ObservationsToJSON
} from '../models/index'

export interface V11FeaturesOfInterestEntityIdGetRequest {
  entityId: string;
  $select?: string;
  $expand?: string;
}

export interface V11FeaturesOfInterestEntityIdObservationsGetRequest {
  entityId: string;
  $skip?: number;
  $top?: number;
  $count?: boolean;
  $select?: string;
  $expand?: string;
  $filter?: string;
}

export interface V11FeaturesOfInterestGetRequest {
  $skip?: number;
  $top?: number;
  $count?: boolean;
  $select?: string;
  $expand?: string;
  $filter?: string;
}

/**
 *
 */
export class FeaturesOfInterestApi extends runtime.BaseAPI {

  /**
   * Returns information about the feature of interest identified by **entityId**
   * Get information about an individual feature of interest
   */
  async v11FeaturesOfInterestEntityIdGetRaw(requestParameters: V11FeaturesOfInterestEntityIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeatureOfInterest>> {
    if (requestParameters['entityId'] == null) {
      throw new runtime.RequiredError(
        'entityId',
        'Required parameter "entityId" was null or undefined when calling v11FeaturesOfInterestEntityIdGet().'
      )
    }

    const queryParameters: any = {}

    if (requestParameters['$select'] != null) {
      queryParameters['$select'] = requestParameters['$select']
    }

    if (requestParameters['$expand'] != null) {
      queryParameters['$expand'] = requestParameters['$expand']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request({
      path: `/v1.1/FeaturesOfInterest({entityId})`.replace(`{${'entityId'}}`, encodeURIComponent(String(requestParameters['entityId']))),
      method: 'GET',
      headers: headerParameters,
      query: queryParameters
    }, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => FeatureOfInterestFromJSON(jsonValue))
  }

  /**
   * Returns information about the feature of interest identified by **entityId**
   * Get information about an individual feature of interest
   */
  async v11FeaturesOfInterestEntityIdGet(requestParameters: V11FeaturesOfInterestEntityIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeatureOfInterest> {
    const response = await this.v11FeaturesOfInterestEntityIdGetRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Returns all observations for the feature of interest identified by **entityId** (subject to any other parameters set)
   * Get all observations for a feature of interest
   */
  async v11FeaturesOfInterestEntityIdObservationsGetRaw(requestParameters: V11FeaturesOfInterestEntityIdObservationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Observations>> {
    if (requestParameters['entityId'] == null) {
      throw new runtime.RequiredError(
        'entityId',
        'Required parameter "entityId" was null or undefined when calling v11FeaturesOfInterestEntityIdObservationsGet().'
      )
    }

    const queryParameters: any = {}

    if (requestParameters['$skip'] != null) {
      queryParameters['$skip'] = requestParameters['$skip']
    }

    if (requestParameters['$top'] != null) {
      queryParameters['$top'] = requestParameters['$top']
    }

    if (requestParameters['$count'] != null) {
      queryParameters['$count'] = requestParameters['$count']
    }

    if (requestParameters['$select'] != null) {
      queryParameters['$select'] = requestParameters['$select']
    }

    if (requestParameters['$expand'] != null) {
      queryParameters['$expand'] = requestParameters['$expand']
    }

    if (requestParameters['$filter'] != null) {
      queryParameters['$filter'] = requestParameters['$filter']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request({
      path: `/v1.1/FeaturesOfInterest({entityId})/Observations`.replace(`{${'entityId'}}`, encodeURIComponent(String(requestParameters['entityId']))),
      method: 'GET',
      headers: headerParameters,
      query: queryParameters
    }, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => ObservationsFromJSON(jsonValue))
  }

  /**
   * Returns all observations for the feature of interest identified by **entityId** (subject to any other parameters set)
   * Get all observations for a feature of interest
   */
  async v11FeaturesOfInterestEntityIdObservationsGet(requestParameters: V11FeaturesOfInterestEntityIdObservationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Observations> {
    const response = await this.v11FeaturesOfInterestEntityIdObservationsGetRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Returns all the features of interest provided by this api (subject to any parameters set)
   * Get all features of interest
   */
  async v11FeaturesOfInterestGetRaw(requestParameters: V11FeaturesOfInterestGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeaturesOfInterest>> {
    const queryParameters: any = {}

    if (requestParameters['$skip'] != null) {
      queryParameters['$skip'] = requestParameters['$skip']
    }

    if (requestParameters['$top'] != null) {
      queryParameters['$top'] = requestParameters['$top']
    }

    if (requestParameters['$count'] != null) {
      queryParameters['$count'] = requestParameters['$count']
    }

    if (requestParameters['$select'] != null) {
      queryParameters['$select'] = requestParameters['$select']
    }

    if (requestParameters['$expand'] != null) {
      queryParameters['$expand'] = requestParameters['$expand']
    }

    if (requestParameters['$filter'] != null) {
      queryParameters['$filter'] = requestParameters['$filter']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request({
      path: `/v1.1/FeaturesOfInterest`,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters
    }, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => FeaturesOfInterestFromJSON(jsonValue))
  }

  /**
   * Returns all the features of interest provided by this api (subject to any parameters set)
   * Get all features of interest
   */
  async v11FeaturesOfInterestGet(requestParameters: V11FeaturesOfInterestGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeaturesOfInterest> {
    const response = await this.v11FeaturesOfInterestGetRaw(requestParameters, initOverrides)
    return await response.value()
  }

}
