/* tslint:disable */
/* eslint-disable */
/**
 * British Geological Survey Sensors API
 * The British Geological Survey (BGS) Sensor API uses Version v1.1 of the OGC SensorThings API.<br><br> Paths/Endpoints that are not currently in use have been excluded, i.e. those relating to Actuators, MultiDatastreams, Tasks and TaskingCapabilities.<br><br> HistoricalLocations have also been removed.<br><br>
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime'
import type {
  Location,
  Locations,
  Things
} from '../models/index'
import {
  LocationFromJSON,
  LocationToJSON,
  LocationsFromJSON,
  LocationsToJSON,
  ThingsFromJSON,
  ThingsToJSON
} from '../models/index'

export interface V11LocationsEntityIdGetRequest {
  entityId: string;
  $select?: string;
  $expand?: string;
}

export interface V11LocationsEntityIdThingsGetRequest {
  entityId: string;
  $skip?: number;
  $top?: number;
  $count?: boolean;
  $select?: string;
  $expand?: string;
  $filter?: string;
}

export interface V11LocationsGetRequest {
  $skip?: number;
  $top?: number;
  $count?: boolean;
  $select?: string;
  $expand?: string;
  $filter?: string;
}

/**
 *
 */
export class LocationsApi extends runtime.BaseAPI {

  /**
   * Returns information about the location identified by **entityId**
   * Get information about an individual location
   */
  async v11LocationsEntityIdGetRaw(requestParameters: V11LocationsEntityIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Location>> {
    if (requestParameters['entityId'] == null) {
      throw new runtime.RequiredError(
        'entityId',
        'Required parameter "entityId" was null or undefined when calling v11LocationsEntityIdGet().'
      )
    }

    const queryParameters: any = {}

    if (requestParameters['$select'] != null) {
      queryParameters['$select'] = requestParameters['$select']
    }

    if (requestParameters['$expand'] != null) {
      queryParameters['$expand'] = requestParameters['$expand']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request({
      path: `/v1.1/Locations({entityId})`.replace(`{${'entityId'}}`, encodeURIComponent(String(requestParameters['entityId']))),
      method: 'GET',
      headers: headerParameters,
      query: queryParameters
    }, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => LocationFromJSON(jsonValue))
  }

  /**
   * Returns information about the location identified by **entityId**
   * Get information about an individual location
   */
  async v11LocationsEntityIdGet(requestParameters: V11LocationsEntityIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Location> {
    const response = await this.v11LocationsEntityIdGetRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Returns information about the thing at the location identified by **entityId**
   * Get information about the thing at the location
   */
  async v11LocationsEntityIdThingsGetRaw(requestParameters: V11LocationsEntityIdThingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Things>> {
    if (requestParameters['entityId'] == null) {
      throw new runtime.RequiredError(
        'entityId',
        'Required parameter "entityId" was null or undefined when calling v11LocationsEntityIdThingsGet().'
      )
    }

    const queryParameters: any = {}

    if (requestParameters['$skip'] != null) {
      queryParameters['$skip'] = requestParameters['$skip']
    }

    if (requestParameters['$top'] != null) {
      queryParameters['$top'] = requestParameters['$top']
    }

    if (requestParameters['$count'] != null) {
      queryParameters['$count'] = requestParameters['$count']
    }

    if (requestParameters['$select'] != null) {
      queryParameters['$select'] = requestParameters['$select']
    }

    if (requestParameters['$expand'] != null) {
      queryParameters['$expand'] = requestParameters['$expand']
    }

    if (requestParameters['$filter'] != null) {
      queryParameters['$filter'] = requestParameters['$filter']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request({
      path: `/v1.1/Locations({entityId})/Things`.replace(`{${'entityId'}}`, encodeURIComponent(String(requestParameters['entityId']))),
      method: 'GET',
      headers: headerParameters,
      query: queryParameters
    }, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => ThingsFromJSON(jsonValue))
  }

  /**
   * Returns information about the thing at the location identified by **entityId**
   * Get information about the thing at the location
   */
  async v11LocationsEntityIdThingsGet(requestParameters: V11LocationsEntityIdThingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Things> {
    const response = await this.v11LocationsEntityIdThingsGetRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Returns all the locations provided by this api (subject to any parameters set)
   * Get all locations
   */
  async v11LocationsGetRaw(requestParameters: V11LocationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Locations>> {
    const queryParameters: any = {}

    if (requestParameters['$skip'] != null) {
      queryParameters['$skip'] = requestParameters['$skip']
    }

    if (requestParameters['$top'] != null) {
      queryParameters['$top'] = requestParameters['$top']
    }

    if (requestParameters['$count'] != null) {
      queryParameters['$count'] = requestParameters['$count']
    }

    if (requestParameters['$select'] != null) {
      queryParameters['$select'] = requestParameters['$select']
    }

    if (requestParameters['$expand'] != null) {
      queryParameters['$expand'] = requestParameters['$expand']
    }

    if (requestParameters['$filter'] != null) {
      queryParameters['$filter'] = requestParameters['$filter']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request({
      path: `/v1.1/Locations`,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters
    }, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => LocationsFromJSON(jsonValue))
  }

  /**
   * Returns all the locations provided by this api (subject to any parameters set)
   * Get all locations
   */
  async v11LocationsGet(requestParameters: V11LocationsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Locations> {
    const response = await this.v11LocationsGetRaw(requestParameters, initOverrides)
    return await response.value()
  }

}
