/* tslint:disable */
/* eslint-disable */
/**
 * British Geological Survey Sensors API
 * The British Geological Survey (BGS) Sensor API uses Version v1.1 of the OGC SensorThings API.<br><br> Paths/Endpoints that are not currently in use have been excluded, i.e. those relating to Actuators, MultiDatastreams, Tasks and TaskingCapabilities.<br><br> HistoricalLocations have also been removed.<br><br>
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime'
import type {
  Datastreams,
  Sensor,
  Sensors
} from '../models/index'
import {
  DatastreamsFromJSON,
  DatastreamsToJSON,
  SensorFromJSON,
  SensorToJSON,
  SensorsFromJSON,
  SensorsToJSON
} from '../models/index'

export interface V11SensorsEntityIdDatastreamsGetRequest {
  entityId: string;
  $skip?: number;
  $top?: number;
  $count?: boolean;
  $select?: string;
  $expand?: string;
  $filter?: string;
}

export interface V11SensorsEntityIdGetRequest {
  entityId: string;
  $select?: string;
  $expand?: string;
}

export interface V11SensorsGetRequest {
  $skip?: number;
  $top?: number;
  $count?: boolean;
  $select?: string;
  $expand?: string;
  $filter?: string;
}

/**
 *
 */
export class SensorsApi extends runtime.BaseAPI {

  /**
   * Returns all datastreams for the sensor type identified by **entityId** (subject to any other parameters set)
   * Get all datastreams for a sensor type
   */
  async v11SensorsEntityIdDatastreamsGetRaw(requestParameters: V11SensorsEntityIdDatastreamsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Datastreams>> {
    if (requestParameters['entityId'] == null) {
      throw new runtime.RequiredError(
        'entityId',
        'Required parameter "entityId" was null or undefined when calling v11SensorsEntityIdDatastreamsGet().'
      )
    }

    const queryParameters: any = {}

    if (requestParameters['$skip'] != null) {
      queryParameters['$skip'] = requestParameters['$skip']
    }

    if (requestParameters['$top'] != null) {
      queryParameters['$top'] = requestParameters['$top']
    }

    if (requestParameters['$count'] != null) {
      queryParameters['$count'] = requestParameters['$count']
    }

    if (requestParameters['$select'] != null) {
      queryParameters['$select'] = requestParameters['$select']
    }

    if (requestParameters['$expand'] != null) {
      queryParameters['$expand'] = requestParameters['$expand']
    }

    if (requestParameters['$filter'] != null) {
      queryParameters['$filter'] = requestParameters['$filter']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request({
      path: `/v1.1/Sensors({entityId})/Datastreams`.replace(`{${'entityId'}}`, encodeURIComponent(String(requestParameters['entityId']))),
      method: 'GET',
      headers: headerParameters,
      query: queryParameters
    }, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => DatastreamsFromJSON(jsonValue))
  }

  /**
   * Returns all datastreams for the sensor type identified by **entityId** (subject to any other parameters set)
   * Get all datastreams for a sensor type
   */
  async v11SensorsEntityIdDatastreamsGet(requestParameters: V11SensorsEntityIdDatastreamsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Datastreams> {
    const response = await this.v11SensorsEntityIdDatastreamsGetRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Returns information about the sensor type identified by **entityId**
   * Get information about an individual sensor type
   */
  async v11SensorsEntityIdGetRaw(requestParameters: V11SensorsEntityIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sensor>> {
    if (requestParameters['entityId'] == null) {
      throw new runtime.RequiredError(
        'entityId',
        'Required parameter "entityId" was null or undefined when calling v11SensorsEntityIdGet().'
      )
    }

    const queryParameters: any = {}

    if (requestParameters['$select'] != null) {
      queryParameters['$select'] = requestParameters['$select']
    }

    if (requestParameters['$expand'] != null) {
      queryParameters['$expand'] = requestParameters['$expand']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request({
      path: `/v1.1/Sensors({entityId})`.replace(`{${'entityId'}}`, encodeURIComponent(String(requestParameters['entityId']))),
      method: 'GET',
      headers: headerParameters,
      query: queryParameters
    }, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => SensorFromJSON(jsonValue))
  }

  /**
   * Returns information about the sensor type identified by **entityId**
   * Get information about an individual sensor type
   */
  async v11SensorsEntityIdGet(requestParameters: V11SensorsEntityIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sensor> {
    const response = await this.v11SensorsEntityIdGetRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Returns all the sensor types provided by this api (subject to any parameters set)
   * Get all sensor types
   */
  async v11SensorsGetRaw(requestParameters: V11SensorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sensors>> {
    const queryParameters: any = {}

    if (requestParameters['$skip'] != null) {
      queryParameters['$skip'] = requestParameters['$skip']
    }

    if (requestParameters['$top'] != null) {
      queryParameters['$top'] = requestParameters['$top']
    }

    if (requestParameters['$count'] != null) {
      queryParameters['$count'] = requestParameters['$count']
    }

    if (requestParameters['$select'] != null) {
      queryParameters['$select'] = requestParameters['$select']
    }

    if (requestParameters['$expand'] != null) {
      queryParameters['$expand'] = requestParameters['$expand']
    }

    if (requestParameters['$filter'] != null) {
      queryParameters['$filter'] = requestParameters['$filter']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request({
      path: `/v1.1/Sensors`,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters
    }, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => SensorsFromJSON(jsonValue))
  }

  /**
   * Returns all the sensor types provided by this api (subject to any parameters set)
   * Get all sensor types
   */
  async v11SensorsGet(requestParameters: V11SensorsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sensors> {
    const response = await this.v11SensorsGetRaw(requestParameters, initOverrides)
    return await response.value()
  }

}
