/* tslint:disable */
/* eslint-disable */
/**
 * British Geological Survey Sensors API
 * The British Geological Survey (BGS) Sensor API uses Version v1.1 of the OGC SensorThings API.<br><br> Paths/Endpoints that are not currently in use have been excluded, i.e. those relating to Actuators, MultiDatastreams, Tasks and TaskingCapabilities.<br><br> HistoricalLocations have also been removed.<br><br>
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Datastream } from './Datastream'
import {
  DatastreamFromJSON,
  DatastreamFromJSONTyped,
  DatastreamToJSON,
  DatastreamToJSONTyped
} from './Datastream'

/**
 *
 * @export
 * @interface Datastreams
 */
export interface Datastreams {
  /**
   * The total number of entities in the entityset
   * @type {number}
   * @memberof Datastreams
   */
  iotCount?: number;
  /**
   * The link to the next page of entities
   * @type {string}
   * @memberof Datastreams
   */
  iotNextLink?: string;
  /**
   *
   * @type {Array<Datastream>}
   * @memberof Datastreams
   */
  value?: Array<Datastream>;
}

/**
 * Check if a given object implements the Datastreams interface.
 */
export function instanceOfDatastreams(value: object): value is Datastreams {
  return true
}

export function DatastreamsFromJSON(json: any): Datastreams {
  return DatastreamsFromJSONTyped(json, false)
}

export function DatastreamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Datastreams {
  if (json == null) {
    return json
  }
  return {

    'iotCount': json['@iot.count'] == null ? undefined : json['@iot.count'],
    'iotNextLink': json['@iot.nextLink'] == null ? undefined : json['@iot.nextLink'],
    'value': json['value'] == null ? undefined : ((json['value'] as Array<any>).map(DatastreamFromJSON))
  }
}

export function DatastreamsToJSON(json: any): Datastreams {
  return DatastreamsToJSONTyped(json, false)
}

export function DatastreamsToJSONTyped(value?: Datastreams | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {

    '@iot.count': value['iotCount'],
    '@iot.nextLink': value['iotNextLink'],
    'value': value['value'] == null ? undefined : ((value['value'] as Array<any>).map(DatastreamToJSON))
  }
}

