/* tslint:disable */
/* eslint-disable */
/**
 * British Geological Survey Sensors API
 * The British Geological Survey (BGS) Sensor API uses Version v1.1 of the OGC SensorThings API.<br><br> Paths/Endpoints that are not currently in use have been excluded, i.e. those relating to Actuators, MultiDatastreams, Tasks and TaskingCapabilities.<br><br> HistoricalLocations have also been removed.<br><br>
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Location } from './Location'
import {
  LocationFromJSON,
  LocationFromJSONTyped,
  LocationToJSON,
  LocationToJSONTyped
} from './Location'

/**
 *
 * @export
 * @interface Locations
 */
export interface Locations {
  /**
   * The total number of entities in the entityset
   * @type {number}
   * @memberof Locations
   */
  iotCount?: number;
  /**
   * The link to the next page of entities
   * @type {string}
   * @memberof Locations
   */
  iotNextLink?: string;
  /**
   *
   * @type {Array<Location>}
   * @memberof Locations
   */
  value?: Array<Location>;
}

/**
 * Check if a given object implements the Locations interface.
 */
export function instanceOfLocations(value: object): value is Locations {
  return true
}

export function LocationsFromJSON(json: any): Locations {
  return LocationsFromJSONTyped(json, false)
}

export function LocationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Locations {
  if (json == null) {
    return json
  }
  return {

    'iotCount': json['@iot.count'] == null ? undefined : json['@iot.count'],
    'iotNextLink': json['@iot.nextLink'] == null ? undefined : json['@iot.nextLink'],
    'value': json['value'] == null ? undefined : ((json['value'] as Array<any>).map(LocationFromJSON))
  }
}

export function LocationsToJSON(json: any): Locations {
  return LocationsToJSONTyped(json, false)
}

export function LocationsToJSONTyped(value?: Locations | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {

    '@iot.count': value['iotCount'],
    '@iot.nextLink': value['iotNextLink'],
    'value': value['value'] == null ? undefined : ((value['value'] as Array<any>).map(LocationToJSON))
  }
}

