/* tslint:disable */
/* eslint-disable */
/**
 * British Geological Survey Sensors API
 * The British Geological Survey (BGS) Sensor API uses Version v1.1 of the OGC SensorThings API.<br><br> Paths/Endpoints that are not currently in use have been excluded, i.e. those relating to Actuators, MultiDatastreams, Tasks and TaskingCapabilities.<br><br> HistoricalLocations have also been removed.<br><br>
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Observation } from './Observation'
import {
  ObservationFromJSON,
  ObservationFromJSONTyped,
  ObservationToJSON,
  ObservationToJSONTyped
} from './Observation'

/**
 *
 * @export
 * @interface Observations
 */
export interface Observations {
  /**
   * The total number of entities in the entityset
   * @type {number}
   * @memberof Observations
   */
  iotCount?: number;
  /**
   * The link to the next page of entities
   * @type {string}
   * @memberof Observations
   */
  iotNextLink?: string;
  /**
   *
   * @type {Array<Observation>}
   * @memberof Observations
   */
  value?: Array<Observation>;
}

/**
 * Check if a given object implements the Observations interface.
 */
export function instanceOfObservations(value: object): value is Observations {
  return true
}

export function ObservationsFromJSON(json: any): Observations {
  return ObservationsFromJSONTyped(json, false)
}

export function ObservationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Observations {
  if (json == null) {
    return json
  }
  return {

    'iotCount': json['@iot.count'] == null ? undefined : json['@iot.count'],
    'iotNextLink': json['@iot.nextLink'] == null ? undefined : json['@iot.nextLink'],
    'value': json['value'] == null ? undefined : ((json['value'] as Array<any>).map(ObservationFromJSON))
  }
}

export function ObservationsToJSON(json: any): Observations {
  return ObservationsToJSONTyped(json, false)
}

export function ObservationsToJSONTyped(value?: Observations | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {

    '@iot.count': value['iotCount'],
    '@iot.nextLink': value['iotNextLink'],
    'value': value['value'] == null ? undefined : ((value['value'] as Array<any>).map(ObservationToJSON))
  }
}

