/* tslint:disable */
/* eslint-disable */
/**
 * British Geological Survey Sensors API
 * The British Geological Survey (BGS) Sensor API uses Version v1.1 of the OGC SensorThings API.<br><br> Paths/Endpoints that are not currently in use have been excluded, i.e. those relating to Actuators, MultiDatastreams, Tasks and TaskingCapabilities.<br><br> HistoricalLocations have also been removed.<br><br>
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { ObservedProperty } from './ObservedProperty'
import {
  ObservedPropertyFromJSON,
  ObservedPropertyFromJSONTyped,
  ObservedPropertyToJSON,
  ObservedPropertyToJSONTyped
} from './ObservedProperty'

/**
 *
 * @export
 * @interface ObservedProperties
 */
export interface ObservedProperties {
  /**
   * The total number of entities in the entityset
   * @type {number}
   * @memberof ObservedProperties
   */
  iotCount?: number;
  /**
   * The link to the next page of entities
   * @type {string}
   * @memberof ObservedProperties
   */
  iotNextLink?: string;
  /**
   *
   * @type {Array<ObservedProperty>}
   * @memberof ObservedProperties
   */
  value?: Array<ObservedProperty>;
}

/**
 * Check if a given object implements the ObservedProperties interface.
 */
export function instanceOfObservedProperties(value: object): value is ObservedProperties {
  return true
}

export function ObservedPropertiesFromJSON(json: any): ObservedProperties {
  return ObservedPropertiesFromJSONTyped(json, false)
}

export function ObservedPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObservedProperties {
  if (json == null) {
    return json
  }
  return {

    'iotCount': json['@iot.count'] == null ? undefined : json['@iot.count'],
    'iotNextLink': json['@iot.nextLink'] == null ? undefined : json['@iot.nextLink'],
    'value': json['value'] == null ? undefined : ((json['value'] as Array<any>).map(ObservedPropertyFromJSON))
  }
}

export function ObservedPropertiesToJSON(json: any): ObservedProperties {
  return ObservedPropertiesToJSONTyped(json, false)
}

export function ObservedPropertiesToJSONTyped(value?: ObservedProperties | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {

    '@iot.count': value['iotCount'],
    '@iot.nextLink': value['iotNextLink'],
    'value': value['value'] == null ? undefined : ((value['value'] as Array<any>).map(ObservedPropertyToJSON))
  }
}

