/* tslint:disable */
/* eslint-disable */
/**
 * British Geological Survey Sensors API
 * The British Geological Survey (BGS) Sensor API uses Version v1.1 of the OGC SensorThings API.<br><br> Paths/Endpoints that are not currently in use have been excluded, i.e. those relating to Actuators, MultiDatastreams, Tasks and TaskingCapabilities.<br><br> HistoricalLocations have also been removed.<br><br>
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Sensor } from './Sensor'
import {
  SensorFromJSON,
  SensorFromJSONTyped,
  SensorToJSON,
  SensorToJSONTyped
} from './Sensor'

/**
 *
 * @export
 * @interface Sensors
 */
export interface Sensors {
  /**
   * The total number of entities in the entityset
   * @type {number}
   * @memberof Sensors
   */
  iotCount?: number;
  /**
   * The link to the next page of entities
   * @type {string}
   * @memberof Sensors
   */
  iotNextLink?: string;
  /**
   *
   * @type {Array<Sensor>}
   * @memberof Sensors
   */
  value?: Array<Sensor>;
}

/**
 * Check if a given object implements the Sensors interface.
 */
export function instanceOfSensors(value: object): value is Sensors {
  return true
}

export function SensorsFromJSON(json: any): Sensors {
  return SensorsFromJSONTyped(json, false)
}

export function SensorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sensors {
  if (json == null) {
    return json
  }
  return {

    'iotCount': json['@iot.count'] == null ? undefined : json['@iot.count'],
    'iotNextLink': json['@iot.nextLink'] == null ? undefined : json['@iot.nextLink'],
    'value': json['value'] == null ? undefined : ((json['value'] as Array<any>).map(SensorFromJSON))
  }
}

export function SensorsToJSON(json: any): Sensors {
  return SensorsToJSONTyped(json, false)
}

export function SensorsToJSONTyped(value?: Sensors | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {

    '@iot.count': value['iotCount'],
    '@iot.nextLink': value['iotNextLink'],
    'value': value['value'] == null ? undefined : ((value['value'] as Array<any>).map(SensorToJSON))
  }
}

