/* tslint:disable */
/* eslint-disable */
/**
 * British Geological Survey Sensors API
 * The British Geological Survey (BGS) Sensor API uses Version v1.1 of the OGC SensorThings API.<br><br> Paths/Endpoints that are not currently in use have been excluded, i.e. those relating to Actuators, MultiDatastreams, Tasks and TaskingCapabilities.<br><br> HistoricalLocations have also been removed.<br><br>
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { SensorProperties } from './SensorProperties'
import {
  SensorPropertiesFromJSON,
  SensorPropertiesFromJSONTyped,
  SensorPropertiesToJSON,
  SensorPropertiesToJSONTyped
} from './SensorProperties'

/**
 *
 * @export
 * @interface Sensor
 */
export interface Sensor {
  /**
   * The Id of the sensor type
   * @type {string}
   * @memberof Sensor
   */
  iotId?: string;
  /**
   * The direct link to the entity
   * @type {string}
   * @memberof Sensor
   */
  iotSelfLink?: string;
  /**
   * A description of the sensor type
   * @type {string}
   * @memberof Sensor
   */
  description?: string;
  /**
   * The encoding type of the 'metadata' property
   * @type {string}
   * @memberof Sensor
   */
  encodingType?: string;
  /**
   * A detailed description of the sensor type (style based on 'encodingType' property)
   * @type {string}
   * @memberof Sensor
   */
  metadata?: string;
  /**
   * The label or name of the sensor type
   * @type {string}
   * @memberof Sensor
   */
  name?: string;
  /**
   *
   * @type {SensorProperties}
   * @memberof Sensor
   */
  properties?: SensorProperties;
}

/**
 * Check if a given object implements the Sensor interface.
 */
export function instanceOfSensor(value: object): value is Sensor {
  return true
}

export function SensorFromJSON(json: any): Sensor {
  return SensorFromJSONTyped(json, false)
}

export function SensorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sensor {
  if (json == null) {
    return json
  }
  return {

    'iotId': json['@iot.id'] == null ? undefined : json['@iot.id'],
    'iotSelfLink': json['@iot.selfLink'] == null ? undefined : json['@iot.selfLink'],
    'description': json['description'] == null ? undefined : json['description'],
    'encodingType': json['encodingType'] == null ? undefined : json['encodingType'],
    'metadata': json['metadata'] == null ? undefined : json['metadata'],
    'name': json['name'] == null ? undefined : json['name'],
    'properties': json['properties'] == null ? undefined : SensorPropertiesFromJSON(json['properties'])
  }
}

export function SensorToJSON(json: any): Sensor {
  return SensorToJSONTyped(json, false)
}

export function SensorToJSONTyped(value?: Sensor | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {

    '@iot.id': value['iotId'],
    '@iot.selfLink': value['iotSelfLink'],
    'description': value['description'],
    'encodingType': value['encodingType'],
    'metadata': value['metadata'],
    'name': value['name'],
    'properties': SensorPropertiesToJSON(value['properties'])
  }
}

