/* tslint:disable */
/* eslint-disable */
/**
 * British Geological Survey Sensors API
 * The British Geological Survey (BGS) Sensor API uses Version v1.1 of the OGC SensorThings API.<br><br> Paths/Endpoints that are not currently in use have been excluded, i.e. those relating to Actuators, MultiDatastreams, Tasks and TaskingCapabilities.<br><br> HistoricalLocations have also been removed.<br><br>
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Thing } from './Thing'
import {
  ThingFromJSON,
  ThingFromJSONTyped,
  ThingToJSON,
  ThingToJSONTyped
} from './Thing'

/**
 *
 * @export
 * @interface Things
 */
export interface Things {
  /**
   * The total number of entities in the entityset
   * @type {number}
   * @memberof Things
   */
  iotCount?: number;
  /**
   * The link to the next page of entities
   * @type {string}
   * @memberof Things
   */
  iotNextLink?: string;
  /**
   *
   * @type {Array<Thing>}
   * @memberof Things
   */
  value?: Array<Thing>;
}

/**
 * Check if a given object implements the Things interface.
 */
export function instanceOfThings(value: object): value is Things {
  return true
}

export function ThingsFromJSON(json: any): Things {
  return ThingsFromJSONTyped(json, false)
}

export function ThingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Things {
  if (json == null) {
    return json
  }
  return {

    'iotCount': json['@iot.count'] == null ? undefined : json['@iot.count'],
    'iotNextLink': json['@iot.nextLink'] == null ? undefined : json['@iot.nextLink'],
    'value': json['value'] == null ? undefined : ((json['value'] as Array<any>).map(ThingFromJSON))
  }
}

export function ThingsToJSON(json: any): Things {
  return ThingsToJSONTyped(json, false)
}

export function ThingsToJSONTyped(value?: Things | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {

    '@iot.count': value['iotCount'],
    '@iot.nextLink': value['iotNextLink'],
    'value': value['value'] == null ? undefined : ((value['value'] as Array<any>).map(ThingToJSON))
  }
}

