/* tslint:disable */
/* eslint-disable */
/**
 * British Geological Survey Sensors API
 * The British Geological Survey (BGS) Sensor API uses Version v1.1 of the OGC SensorThings API.<br><br> Paths/Endpoints that are not currently in use have been excluded, i.e. those relating to Actuators, MultiDatastreams, Tasks and TaskingCapabilities.<br><br> HistoricalLocations have also been removed.<br><br>
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Datastream } from './Datastream'
import {
  DatastreamFromJSON,
  DatastreamFromJSONTyped,
  DatastreamToJSON,
  DatastreamToJSONTyped
} from './Datastream'
import type { Location } from './Location'
import {
  LocationFromJSON,
  LocationFromJSONTyped,
  LocationToJSON,
  LocationToJSONTyped
} from './Location'
import type { ThingProperties } from './ThingProperties'
import {
  ThingPropertiesFromJSON,
  ThingPropertiesFromJSONTyped,
  ThingPropertiesToJSON,
  ThingPropertiesToJSONTyped
} from './ThingProperties'

/**
 *
 * @export
 * @interface Thing
 */
export interface Thing {
  /**
   * The Id of the thing
   * @type {string}
   * @memberof Thing
   */
  iotId?: string;
  /**
   * The direct link to the entity
   * @type {string}
   * @memberof Thing
   */
  iotSelfLink?: string;
  /**
   *
   * @type {Array<Datastream>}
   * @memberof Thing
   */
  datastreams?: Array<Datastream>;
  /**
   * The total number of entities in the entityset
   * @type {number}
   * @memberof Thing
   */
  datastreamsiotCount?: number;
  /**
   * A link to a related entity or entity set
   * @type {string}
   * @memberof Thing
   */
  datastreamsiotNavigationLink?: string;
  /**
   * The link to the next page of entities
   * @type {string}
   * @memberof Thing
   */
  datastreamsiotNextLink?: string;
  /**
   *
   * @type {Array<Location>}
   * @memberof Thing
   */
  locations?: Array<Location>;
  /**
   * The total number of entities in the entityset
   * @type {number}
   * @memberof Thing
   */
  locationsiotCount?: number;
  /**
   * A link to a related entity or entity set
   * @type {string}
   * @memberof Thing
   */
  locationsiotNavigationLink?: string;
  /**
   * The link to the next page of entities
   * @type {string}
   * @memberof Thing
   */
  locationsiotNextLink?: string;
  /**
   * A description of the thing
   * @type {string}
   * @memberof Thing
   */
  description?: string;
  /**
   * The label or name of the thing
   * @type {string}
   * @memberof Thing
   */
  name?: string;
  /**
   *
   * @type {ThingProperties}
   * @memberof Thing
   */
  properties?: ThingProperties;
}

/**
 * Check if a given object implements the Thing interface.
 */
export function instanceOfThing(value: object): value is Thing {
  return true
}

export function ThingFromJSON(json: any): Thing {
  return ThingFromJSONTyped(json, false)
}

export function ThingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Thing {
  if (json == null) {
    return json
  }
  return {

    'iotId': json['@iot.id'] == null ? undefined : json['@iot.id'],
    'iotSelfLink': json['@iot.selfLink'] == null ? undefined : json['@iot.selfLink'],
    'datastreams': json['Datastreams'] == null ? undefined : ((json['Datastreams'] as Array<any>).map(DatastreamFromJSON)),
    'datastreamsiotCount': json['Datastreams@iot.count'] == null ? undefined : json['Datastreams@iot.count'],
    'datastreamsiotNavigationLink': json['Datastreams@iot.navigationLink'] == null ? undefined : json['Datastreams@iot.navigationLink'],
    'datastreamsiotNextLink': json['Datastreams@iot.nextLink'] == null ? undefined : json['Datastreams@iot.nextLink'],
    'locations': json['Locations'] == null ? undefined : ((json['Locations'] as Array<any>).map(LocationFromJSON)),
    'locationsiotCount': json['Locations@iot.count'] == null ? undefined : json['Locations@iot.count'],
    'locationsiotNavigationLink': json['Locations@iot.navigationLink'] == null ? undefined : json['Locations@iot.navigationLink'],
    'locationsiotNextLink': json['Locations@iot.nextLink'] == null ? undefined : json['Locations@iot.nextLink'],
    'description': json['description'] == null ? undefined : json['description'],
    'name': json['name'] == null ? undefined : json['name'],
    'properties': json['properties'] == null ? undefined : ThingPropertiesFromJSON(json['properties'])
  }
}

export function ThingToJSON(json: any): Thing {
  return ThingToJSONTyped(json, false)
}

export function ThingToJSONTyped(value?: Thing | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {

    '@iot.id': value['iotId'],
    '@iot.selfLink': value['iotSelfLink'],
    'Datastreams': value['datastreams'] == null ? undefined : ((value['datastreams'] as Array<any>).map(DatastreamToJSON)),
    'Datastreams@iot.count': value['datastreamsiotCount'],
    'Datastreams@iot.navigationLink': value['datastreamsiotNavigationLink'],
    'Datastreams@iot.nextLink': value['datastreamsiotNextLink'],
    'Locations': value['locations'] == null ? undefined : ((value['locations'] as Array<any>).map(LocationToJSON)),
    'Locations@iot.count': value['locationsiotCount'],
    'Locations@iot.navigationLink': value['locationsiotNavigationLink'],
    'Locations@iot.nextLink': value['locationsiotNextLink'],
    'description': value['description'],
    'name': value['name'],
    'properties': ThingPropertiesToJSON(value['properties'])
  }
}

